config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get '/restricted', to: 'home#restricted'
  get 'home/index'
  devise_for :users

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include CurrentUserConcern

    def after_sign_in_path_for(resource)
      restricted_path
    end

end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
    extend ActiveSupport::Concern
  
    def current_user
      super || guest_user
    end
  
    def guest_user
      OpenStruct.new(name: "Guest User",
                    firstname: "Guest",
                    lastname: "User",
                    email: "guest@example.com",
                    role: "guest"
                    )
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [ :restricted ]

  def index
  end

  def restricted
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def active_class(link_path)
        current_page?(link_path) ? "active" : ""
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% content_for(:html_title) { 'Public Content' } %>

<h1>Public Content</h1>
<p>Find me in app/views/home/index.html.erb <br />>Anyone who navigates to this page can see this content. It is public!</p>

app/views/home/restricted.html.erb
<% content_for(:html_title) { 'Restricted Content' } %>

<h1>Restricted Content</h1>
<p>Only authenticated individuals can see this content. It's restricted!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:html_title) ? yield(:html_title) : "Default" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "/shared/navbar" %>
    <div class="container-fluid"> 
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-color: #e3f2fd;">
  <!-- <div class="containter-fluid"> -->
        
            <%= image_tag ("rails_not_snails.png") %>   
            <!-- <a class="navbar-brand" href="/">Authentico</a> -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
        <div class="collapse navbar-collapse ps-4" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <!-- Display contextual menu items -->
                <% if current_user.is_a?(User) %>
                    <%# if current_user.role == "admin" || current_user.role == "manager" %>
                    <li class="nav-item">
                        <%= link_to "Public Content", home_index_path, class: "nav-link #{ active_class(home_index_path) }" %>
                    </li>
                    <li class="nav-item ">
                        <%= link_to "Private Content", restricted_path, class: "nav-link #{ active_class(restricted_path) }" %>
                    </li>
                    <%# else %>
                <% end %>
                
                <!-- Login Items -->
                <li class="nav-item">
                    <% if current_user.is_a?(User) %>
                    <%= link_to "Log Out", destroy_user_session_path, class: "nav-link" %>
                    <% else %>
                    <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
                    <% end %>
                </li>
            </ul>
        </div>
                    <!-- Display name of current_user -->
        <% if user_signed_in? %>
            <span class="navbar-text me-4">
            Welcome, <%= current_user.email %>
            </span>
        <% end %>
    <!-- </div> -->
</nav>